// Generated by scaffold Phase-2 from docs/tech-design/library-demo.md
// Source: <module name="Catalog"><entities>Author</entities></module>
// Devs: edit freely. Re-running Phase-2 overwrites. Commit before re-run.
using System;

namespace Library.Domain.Catalog;

public sealed class Author
{
    public Guid Id { get; private set; }
    public string Name { get; private set; } = default!;
    public DateTimeOffset CreatedAt { get; private set; }

    private Author() { } // Object-initializer use by Create. Dapper hydrates AuthorRow, not the Domain entity.

    // TODO: invariants from tech-design — name is non-empty.
    public static Author Create(string name)
        => throw new NotImplementedException("TODO: enforce Author invariants");
}
