// Generated by scaffold Phase-2 from docs/tech-design/library-demo.md
// Source: <module name="Catalog"><contracts>HoldResponse</contracts></module>
// Devs: edit freely. Re-running Phase-2 overwrites. Commit before re-run.

using System;
using Library.Domain.Catalog;

namespace Library.Api.Catalog.Contracts;

public sealed record HoldResponse(
    Guid Id,
    Guid TitleId,
    Guid PatronId,
    HoldStatus Status,
    DateTimeOffset CreatedAt
);
